FROM node:21.6-alpine AS build
WORKDIR /usr/app

ARG PUBLIC_APP_ENV=$PUBLIC_APP_ENV
ARG DATABASE_URL=$DATABASE_URL
ARG REDIS_URL=$REDIS_URL
ARG JWT_SESSION_SECRET=$JWT_SESSION_SECRET
ARG S3_BUCKET=$S3_BUCKET
ARG S3_REGION=$S3_REGION
ARG S3_ACCESS_KEY=$S3_ACCESS_KEY
ARG S3_SECRET_KEY=$S3_SECRET_KEY
ARG S3_ENDPOINT=$S3_ENDPOINT
ARG SENTRY_ORG=$SENTRY_ORG
ARG SENTRY_PROJECT=$SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN

ENV PUBLIC_APP_ENV=${PUBLIC_APP_ENV}
ENV DATABASE_URL=${DATABASE_URL}
ENV REDIS_URL=${REDIS_URL}
ENV JWT_SESSION_SECRET=${JWT_SESSION_SECRET}
ENV S3_BUCKET=${S3_BUCKET}
ENV S3_REGION=${S3_REGION}
ENV S3_ACCESS_KEY=${S3_ACCESS_KEY}
ENV S3_SECRET_KEY=${S3_SECRET_KEY}
ENV S3_ENDPOINT=${S3_ENDPOINT}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

RUN echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
RUN echo $PUBLIC_APP_ENV
RUN echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

COPY ./ ./

RUN npm install
RUN npm run build

FROM node:21.6-alpine
WORKDIR /usr/app

ARG PUBLIC_APP_ENV=$PUBLIC_APP_ENV
ARG DATABASE_URL=$DATABASE_URL
ARG REDIS_URL=$REDIS_URL
ARG JWT_SESSION_SECRET=$JWT_SESSION_SECRET
ARG S3_BUCKET=$S3_BUCKET
ARG S3_REGION=$S3_REGION
ARG S3_ACCESS_KEY=$S3_ACCESS_KEY
ARG S3_SECRET_KEY=$S3_SECRET_KEY
ARG S3_ENDPOINT=$S3_ENDPOINT
ARG SENTRY_ORG=$SENTRY_ORG
ARG SENTRY_PROJECT=$SENTRY_PROJECT
ARG SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN

ENV PUBLIC_APP_ENV=${PUBLIC_APP_ENV}
ENV DATABASE_URL=${DATABASE_URL}
ENV REDIS_URL=${REDIS_URL}
ENV JWT_SESSION_SECRET=${JWT_SESSION_SECRET}
ENV S3_BUCKET=${S3_BUCKET}
ENV S3_REGION=${S3_REGION}
ENV S3_ACCESS_KEY=${S3_ACCESS_KEY}
ENV S3_SECRET_KEY=${S3_SECRET_KEY}
ENV S3_ENDPOINT=${S3_ENDPOINT}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

COPY --from=build /usr/app/package.json ./
COPY --from=build /usr/app/package-lock.json ./
COPY --from=build /usr/app/build ./build

RUN npm install --omit dev
RUN npx prisma migrate deploy

EXPOSE 3000
CMD ["node", "build"]

