name: Deploy to Production

on:
    repository_dispatch:
        types: [deploy_app]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v4

            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            - run: docker compose down --rmi all --volumes --remove-orphans
            - 
              env: 
                DATABASE_URL: ${{secrets.DATABASE_URL}}
                JWT_SESSION_SECRET: ${{secrets.JWT_SESSION_SECRET}}
                PUBLIC_APP_ENV: ${{secrets.PUBLIC_APP_ENV}}
                S3_ACCESS_KEY: ${{secrets.S3_ACCESS_KEY}}
                S3_BUCKET: ${{secrets.S3_BUCKET}}
                S3_ENDPOINT: ${{secrets.S3_ENDPOINT}}
                S3_REGION: ${{secrets.S3_REGION}}
                S3_SECRET_KEY: ${{secrets.S3_SECRET_KEY}}
              run: docker compose up -d --build