name: Publish Docker Image

on:
    push:
        branches:
            - main

jobs:
    docker:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v4
    
            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
    
            - 
                name: Build and push Docker image
                uses: docker/build-push-action@v5
                with:
                    push: true
                    tags: iamthewraith/yumyum:latest

    trigger-deploy:
        permissions: write-all
        name: Trigger Deployment to Production
        runs-on: ubuntu-latest
        needs: docker
        steps:
            -
                name: Trigger Deployment
                run: |
                    curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
                    -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    https://api.github.com/repos/iamthe-Wraith/yumyum-recipes/dispatches \
                    -d '{"event_type": "deploy_app"}'                   
